# Generated by Django 4.0.1 on 2022-05-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_shop_verified',
            field=models.BooleanField(default=False),
        ),
    ]
