# Generated by Django 4.0.1 on 2022-05-19 03:55

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_card_number_order_expire_order_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=creditcards.models.CardNumberField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='expire',
            field=creditcards.models.CardExpiryField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='security_code',
            field=creditcards.models.SecurityCodeField(max_length=4),
        ),
    ]
