# Generated by Django 4.0.1 on 2022-05-19 14:12

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_card_number_alter_order_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='expire',
            field=creditcards.models.CardExpiryField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='security_code',
            field=creditcards.models.SecurityCodeField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
