# Generated by Django 4.0.1 on 2022-05-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_card_number_alter_order_expire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('onroad', 'onroad'), ('delivered', 'delivered')], default=('pending', 'pending'), max_length=10),
        ),
    ]
