# Generated by Django 4.0.1 on 2022-05-19 14:57

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=creditcards.models.CardNumberField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expire',
            field=creditcards.models.CardExpiryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='security_code',
            field=creditcards.models.SecurityCodeField(blank=True, max_length=4, null=True),
        ),
    ]
