# Generated by Django 4.0.1 on 2022-05-19 15:00

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_status_alter_order_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('onroad', 'onroad'), ('delivered', 'delivered')], default=('pending', 'pending'), max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=creditcards.models.CardNumberField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='expire',
            field=creditcards.models.CardExpiryField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='security_code',
            field=creditcards.models.SecurityCodeField(max_length=4),
        ),
    ]
