# Generated by Django 4.0.1 on 2022-05-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_status_alter_order_card_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
